### ISSUE TITLE
Val cannot be reassigned

### ISSUE THREAD

**Issue by ghost** [mplacona/Droidagram#4]
your code doesn't work. Please update it with correct code. The problem is occurring here:

`viewFinder.surfaceTexture = it.surfaceTexture`

Best

**Comment by mplacona** [comment]
Hey just send me a PR with a fix and I'll happily merge!

Thanks

**Comment by ghost** [comment]
Code still doesn't work but I have decided to use some other method to achieve similar results. Therefore, closing.
